### ISSUE TITLE
Repeating section not showing data

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#528] opened 2021-11-05 12:37 UTC
I figured out what was causing this.  This was an old workflow that included both group and repeat properties.  Removing the group property fixed the display issue.  I think this is still a bug, since we might want one or more groups within a repeating section.  So let's make that work.

In the RSC/HIRE workflow, the _Enter XRay_ User Task is a repeating section.  Information entered in a section is not displayed on the main page.  This is what is displayed:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ae07f2be-42e9-445f-a5e6-8afe4f91534f)

Even though there is information entered:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/43757e61-6c1e-4406-85e1-4861803a6a9e)

**Comment by calexh-sar** [comment] 2021-11-05 13:31
Same thing is happening in the CT User Task:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/76902d39-b4c3-4f64-9e60-ce11490d30dd)

**Comment by Leashys** [comment] 2021-11-09 16:19
Moving to icebox. For now i will write a new ticket that makes repeat + group a validation error. When we improve our form builder, this would be much more managable to accomplish :-)

**Comment by danfunk** [comment] 2022-04-28 14:41
duplicate of 550

**Closed as completed by danfunk** 2022-04-28 14:41 UTC
Labels: bug
