### ISSUE TITLE
Replace 'libraries' and 'standalone' tags on workflow spec with a single 'workflowspectype' field

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#396] opened 2021-07-22 13:59 UTC
We will need to change frontend (where you change the types - make that a dropdown)
libraries - to consolidate the fields
cr_connect_workflow - ​/workflow-specification  to allow a user to select only those specific types of workflowspecs

replace /workflow-specification​/standalone and /workflow-specification​/libraries with the previous - and all places that use these endpoints.

**Comment by Leashys** [comment] 2021-08-25 19:42
I just wrote a ticket #438 that goes hand in hand with this one :)

**Comment by danfunk** [comment] 2022-04-28 14:55
closed as duplicate of #438

**Closed as completed by danfunk** 2022-04-28 14:55 UTC
