### ISSUE TITLE
Study document that becomes unlinked from the documents.xls file

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#327] opened 2021-05-10 18:55 UTC
It is possible for the list of uploadable documents to change over time.
If someone removes a document as an option, anyone that uploaded a file and associated it with this category will result in a key error like the following:
https://sentry.io/organizations/sartography/issues/2380466102/?project=5260915&referrer=slack

We should account for this eventually and handle it in some sensible way.

**Comment by cullerton** [comment] 2021-06-07 18:35
It looks like someone worked on this.

```
    for file in files:
        if file.irb_doc_code in doc_dict:
            doc_code = doc_dict[file.irb_doc_code]
        else:
            doc_code = {'category1': "Unknown", 'category2': None, 'category3': None}

```

**Comment by calexh-sar** [comment] 2021-07-02 14:01
@cullerton don't know of a way I can test this one. Would you pls either provide info on how I can or just close this ticket if you can confirm it has been released and working as designed.

**Comment by cullerton** [comment] 2021-07-02 15:10
@calexh-sar This is definitely difficult to test. 
Maybe we ask about it in post scrum Tuesday. 
Otherwise, I will close this ticket.

**Comment by calexh-sar** [comment] 2021-07-02 15:40
@cullerton I put it on the post scrum agenda for Tuesday.

**Closed as completed** 2021-07-06 13:33 UTC
